# -*- coding: utf-8 -*-
"""Graficar .txt en Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCSpxP2jyt7xzY8xNNWDplsC_rEDpZ0i
"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar los datos desde el archivo
filename = "S_I_750.txt"  # Asegúrate de que el archivo está en la ruta correcta
data = pd.read_csv(filename, delimiter="\t")  # Ajustar el delimitador si es necesario

# Extraer columnas
tiempo_us = data.iloc[:, 0]  # Tiempo en µs
voltaje = data.iloc[:, 1]  # Voltaje en V

# Crear la figura con stem y línea conectando los puntos
plt.figure(figsize=(10, 5))
plt.stem(tiempo_us, voltaje, linefmt='g-', markerfmt='go', basefmt='r-')  # Stem en verde
plt.plot(tiempo_us, voltaje, 'r-', linewidth=1.2, alpha=0.8)  # Línea roja

# Personalización del gráfico
plt.grid(True, linestyle="--", alpha=0.6)
plt.xlabel('Tiempo (µs)')  # Etiqueta corregida
plt.ylabel('Voltaje (V)')
plt.title('Señal Muestras')
plt.xlim([tiempo_us.min(), tiempo_us.max()])  # Ajustar eje X automáticamente
plt.ylim([voltaje.min() - 0.1, voltaje.max() + 0.1])  # Ajustar eje Y con margen

# Mostrar la gráfica
plt.show()